// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ7h9KsitKBpYBMMaWDmeUPbHjvBzwckk',
    appId: '1:272564929576:web:4554220d404c8bc4a4211d',
    messagingSenderId: '272564929576',
    projectId: 'first-flutter-6a7d8',
    authDomain: 'first-flutter-6a7d8.firebaseapp.com',
    storageBucket: 'first-flutter-6a7d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhRdoB_EgSw0zeqFWdn76gfXvjFg-EFgQ',
    appId: '1:272564929576:android:be048317a1e64803a4211d',
    messagingSenderId: '272564929576',
    projectId: 'first-flutter-6a7d8',
    storageBucket: 'first-flutter-6a7d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSf8qvoM417PR6LZqV9hzvEssKAzGx4lo',
    appId: '1:272564929576:ios:030662c2e69b6cc3a4211d',
    messagingSenderId: '272564929576',
    projectId: 'first-flutter-6a7d8',
    storageBucket: 'first-flutter-6a7d8.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSf8qvoM417PR6LZqV9hzvEssKAzGx4lo',
    appId: '1:272564929576:ios:030662c2e69b6cc3a4211d',
    messagingSenderId: '272564929576',
    projectId: 'first-flutter-6a7d8',
    storageBucket: 'first-flutter-6a7d8.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
